name: otw
version: 0.1.1
config-version: 2
profile: otw

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: target
clean-targets:
  - target
  - dbt_packages

on-run-start:
  - "{{ create_health_parsing_functions() }}"

models:
  otw:
    +persist_docs:
      relation: true
      columns: true
    staging:
      +materialized: table
      +schema: staging
      +tags: ["staging", "health"]
    intermediate:
      +materialized: table
      +schema: intermediate
      +tags: ["intermediate", "health"]

seeds:
  otw:
    +schema: staging
    +tags: ["staging", "health"]
