{{ config(tags=['garmin', 'health', 'staging']) }}

with source_records as (
    select
      id as raw_record_id,
      account_id,
      connector_config_id,
      sync_task_id,
      connector_id,
      source_stream,
      external_id as source_external_id,
      source_record_date,
      source_record_at,
      source_updated_at,
      collected_at,
      payload_hash,
      created_at as raw_created_at,
      updated_at as raw_updated_at,
      payload_jsonb
    from {{ source('raw_health', 'health_snapshot_record') }}
    where connector_id = 'garmin-connect'
      and source_stream = 'daily_summary'
)
select
  raw_record_id,
  account_id,
  connector_config_id,
  sync_task_id,
  connector_id,
  source_stream,
  source_external_id,
  source_record_date,
  source_record_at,
  source_updated_at,
  collected_at,
  payload_hash,
  raw_created_at,
  raw_updated_at,
  {{ health_clean_text("payload_jsonb ->> 'userProfileId'") }} as user_profile_id,
  {{ health_clean_text("payload_jsonb ->> 'userDailySummaryId'") }} as user_daily_summary_id,
  {{ health_clean_text("payload_jsonb ->> 'calendarDate'") }} as calendar_date,
  {{ health_clean_text("payload_jsonb ->> 'uuid'") }} as summary_uuid,
  {{ health_clean_text("payload_jsonb ->> 'source'") }} as summary_source,
  {{ health_clean_text("payload_jsonb ->> 'displayName'") }} as display_name,
  {{ health_json_try_numeric("payload_jsonb -> 'totalKilocalories'") }} as total_kilocalories,
  {{ health_json_try_numeric("payload_jsonb -> 'activeKilocalories'") }} as active_kilocalories,
  {{ health_json_try_numeric("payload_jsonb -> 'bmrKilocalories'") }} as bmr_kilocalories,
  {{ health_json_try_numeric("payload_jsonb -> 'wellnessKilocalories'") }} as wellness_kilocalories,
  {{ health_json_try_numeric("payload_jsonb -> 'burnedKilocalories'") }} as burned_kilocalories,
  {{ health_json_try_numeric("payload_jsonb -> 'consumedKilocalories'") }} as consumed_kilocalories,
  {{ health_json_try_numeric("payload_jsonb -> 'remainingKilocalories'") }} as remaining_kilocalories,
  {{ health_json_try_numeric("payload_jsonb -> 'netCalorieGoal'") }} as net_calorie_goal,
  {{ health_json_try_numeric("payload_jsonb -> 'netRemainingKilocalories'") }} as net_remaining_kilocalories,
  {{ health_json_try_bigint("payload_jsonb -> 'totalSteps'") }} as total_steps,
  {{ health_json_try_bigint("payload_jsonb -> 'dailyStepGoal'") }} as daily_step_goal,
  {{ health_json_try_numeric("payload_jsonb -> 'totalDistanceMeters'") }} as total_distance_meters,
  {{ health_json_try_numeric("payload_jsonb -> 'wellnessDistanceMeters'") }} as wellness_distance_meters,
  {{ health_json_try_numeric("payload_jsonb -> 'wellnessActiveKilocalories'") }} as wellness_active_kilocalories,
  {{ health_clean_text("payload_jsonb ->> 'wellnessStartTimeGmt'") }} as wellness_start_time_gmt,
  {{ health_clean_text("payload_jsonb ->> 'wellnessEndTimeGmt'") }} as wellness_end_time_gmt,
  {{ health_clean_text("payload_jsonb ->> 'wellnessStartTimeLocal'") }} as wellness_start_time_local,
  {{ health_clean_text("payload_jsonb ->> 'wellnessEndTimeLocal'") }} as wellness_end_time_local,
  {{ health_json_try_bigint("payload_jsonb -> 'durationInMilliseconds'") }} as duration_in_milliseconds,
  {{ health_clean_text("payload_jsonb ->> 'wellnessDescription'") }} as wellness_description,
  {{ health_json_try_bigint("payload_jsonb -> 'highlyActiveSeconds'") }} as highly_active_seconds,
  {{ health_json_try_bigint("payload_jsonb -> 'activeSeconds'") }} as active_seconds,
  {{ health_json_try_bigint("payload_jsonb -> 'sedentarySeconds'") }} as sedentary_seconds,
  {{ health_json_try_bigint("payload_jsonb -> 'sleepingSeconds'") }} as sleeping_seconds,
  {{ health_json_try_boolean("payload_jsonb -> 'includesWellnessData'") }} as includes_wellness_data,
  {{ health_json_try_boolean("payload_jsonb -> 'includesActivityData'") }} as includes_activity_data,
  {{ health_json_try_boolean("payload_jsonb -> 'includesCalorieConsumedData'") }} as includes_calorie_consumed_data,
  {{ health_json_try_boolean("payload_jsonb -> 'privacyProtected'") }} as privacy_protected,
  {{ health_json_try_integer("payload_jsonb -> 'moderateIntensityMinutes'") }} as moderate_intensity_minutes,
  {{ health_json_try_integer("payload_jsonb -> 'vigorousIntensityMinutes'") }} as vigorous_intensity_minutes,
  {{ health_json_try_integer("payload_jsonb -> 'intensityMinutesGoal'") }} as intensity_minutes_goal,
  {{ health_json_try_numeric("payload_jsonb -> 'floorsAscendedInMeters'") }} as floors_ascended_in_meters,
  {{ health_json_try_numeric("payload_jsonb -> 'floorsDescendedInMeters'") }} as floors_descended_in_meters,
  {{ health_json_try_integer("payload_jsonb -> 'floorsAscended'") }} as floors_ascended,
  {{ health_json_try_integer("payload_jsonb -> 'floorsDescended'") }} as floors_descended,
  {{ health_json_try_integer("payload_jsonb -> 'userFloorsAscendedGoal'") }} as user_floors_ascended_goal,
  {{ health_json_try_integer("payload_jsonb -> 'minHeartRate'") }} as min_heart_rate,
  {{ health_json_try_integer("payload_jsonb -> 'maxHeartRate'") }} as max_heart_rate,
  {{ health_json_try_integer("payload_jsonb -> 'abnormalHeartRateAlertsCount'") }} as abnormal_heart_rate_alerts_count,
  {{ health_json_try_integer("payload_jsonb -> 'restingHeartRate'") }} as resting_heart_rate,
  {{ health_json_try_integer("payload_jsonb -> 'lastSevenDaysAvgRestingHeartRate'") }} as last_seven_days_avg_resting_heart_rate,
  {{ health_json_try_numeric("payload_jsonb -> 'averageStressLevel'") }} as average_stress_level,
  {{ health_json_try_numeric("payload_jsonb -> 'maxStressLevel'") }} as max_stress_level,
  {{ health_json_try_numeric("payload_jsonb -> 'stressPercentage'") }} as stress_percentage,
  {{ health_json_try_bigint("payload_jsonb -> 'stressDuration'") }} as stress_duration,
  {{ health_json_try_numeric("payload_jsonb -> 'activityStressPercentage'") }} as activity_stress_percentage,
  {{ health_json_try_bigint("payload_jsonb -> 'restStressDuration'") }} as rest_stress_duration,
  {{ health_json_try_numeric("payload_jsonb -> 'restStressPercentage'") }} as rest_stress_percentage,
  {{ health_json_try_bigint("payload_jsonb -> 'activityStressDuration'") }} as activity_stress_duration,
  {{ health_json_try_bigint("payload_jsonb -> 'uncategorizedStressDuration'") }} as uncategorized_stress_duration,
  {{ health_json_try_numeric("payload_jsonb -> 'uncategorizedStressPercentage'") }} as uncategorized_stress_percentage,
  {{ health_json_try_bigint("payload_jsonb -> 'totalStressDuration'") }} as total_stress_duration,
  {{ health_json_try_bigint("payload_jsonb -> 'lowStressDuration'") }} as low_stress_duration,
  {{ health_json_try_numeric("payload_jsonb -> 'lowStressPercentage'") }} as low_stress_percentage,
  {{ health_json_try_bigint("payload_jsonb -> 'mediumStressDuration'") }} as medium_stress_duration,
  {{ health_json_try_numeric("payload_jsonb -> 'mediumStressPercentage'") }} as medium_stress_percentage,
  {{ health_json_try_bigint("payload_jsonb -> 'highStressDuration'") }} as high_stress_duration,
  {{ health_json_try_numeric("payload_jsonb -> 'highStressPercentage'") }} as high_stress_percentage,
  {{ health_clean_text("payload_jsonb ->> 'stressQualifier'") }} as stress_qualifier,
  {{ health_json_try_bigint("payload_jsonb -> 'measurableAwakeDuration'") }} as measurable_awake_duration,
  {{ health_json_try_bigint("payload_jsonb -> 'measurableAsleepDuration'") }} as measurable_asleep_duration,
  {{ health_clean_text("payload_jsonb ->> 'lastSyncTimestampGMT'") }} as last_sync_timestamp_gmt,
  {{ health_json_try_numeric("payload_jsonb -> 'minAvgHeartRate'") }} as min_avg_heart_rate,
  {{ health_json_try_numeric("payload_jsonb -> 'maxAvgHeartRate'") }} as max_avg_heart_rate,
  {{ health_json_try_numeric("payload_jsonb -> 'averageMonitoringEnvironmentAltitude'") }} as average_monitoring_environment_altitude,
  {{ health_json_try_numeric("payload_jsonb -> 'bodyBatteryAtWakeTime'") }} as body_battery_at_wake_time,
  {{ health_json_try_numeric("payload_jsonb -> 'bodyBatteryChargedValue'") }} as body_battery_charged_value,
  {{ health_json_try_numeric("payload_jsonb -> 'bodyBatteryDrainedValue'") }} as body_battery_drained_value,
  {{ health_json_try_numeric("payload_jsonb -> 'bodyBatteryDuringSleep'") }} as body_battery_during_sleep,
  {{ health_json_try_numeric("payload_jsonb -> 'bodyBatteryHighestValue'") }} as body_battery_highest_value,
  {{ health_json_try_numeric("payload_jsonb -> 'bodyBatteryLowestValue'") }} as body_battery_lowest_value,
  {{ health_json_try_numeric("payload_jsonb -> 'bodyBatteryMostRecentValue'") }} as body_battery_most_recent_value,
  {{ health_json_try_integer("payload_jsonb -> 'bodyBatteryVersion'") }} as body_battery_version,
  {{ health_json_try_numeric("payload_jsonb -> 'averageSpo2'") }} as average_spo2,
  {{ health_json_try_numeric("payload_jsonb -> 'latestSpo2'") }} as latest_spo2,
  {{ health_json_try_numeric("payload_jsonb -> 'lowestSpo2'") }} as lowest_spo2,
  {{ health_clean_text("payload_jsonb ->> 'latestSpo2ReadingTimeGmt'") }} as latest_spo2_reading_time_gmt,
  {{ health_clean_text("payload_jsonb ->> 'latestSpo2ReadingTimeLocal'") }} as latest_spo2_reading_time_local,
  {{ health_json_try_numeric("payload_jsonb -> 'avgWakingRespirationValue'") }} as avg_waking_respiration_value,
  {{ health_json_try_numeric("payload_jsonb -> 'highestRespirationValue'") }} as highest_respiration_value,
  {{ health_json_try_numeric("payload_jsonb -> 'lowestRespirationValue'") }} as lowest_respiration_value,
  {{ health_clean_text("payload_jsonb ->> 'latestRespirationTimeGMT'") }} as latest_respiration_time_gmt,
  {{ health_json_try_numeric("payload_jsonb -> 'latestRespirationValue'") }} as latest_respiration_value,
  {{ health_json_try_integer("payload_jsonb -> 'respirationAlgorithmVersion'") }} as respiration_algorithm_version,
  {{ health_json_try_numeric("payload_jsonb -> 'restingCaloriesFromActivity'") }} as resting_calories_from_activity,
  {{ health_json_try_integer("payload_jsonb #> '{rule,typeId}'") }} as rule_type_id,
  {{ health_clean_text("payload_jsonb #>> '{rule,typeKey}'") }} as rule_type_key

from source_records
