{{ config(tags=['garmin', 'health', 'staging']) }}

with source_records as (
    select
      id as raw_record_id,
      account_id,
      connector_config_id,
      sync_task_id,
      connector_id,
      source_stream,
      external_id as source_external_id,
      source_record_date,
      source_record_at,
      source_updated_at,
      collected_at,
      payload_hash,
      created_at as raw_created_at,
      updated_at as raw_updated_at,
      payload_jsonb
    from {{ source('raw_health', 'health_snapshot_record') }}
    where connector_id = 'garmin-connect'
      and source_stream = 'profile'
)
select
  raw_record_id,
  account_id,
  connector_config_id,
  sync_task_id,
  connector_id,
  source_stream,
  source_external_id,
  source_record_date,
  source_record_at,
  source_updated_at,
  collected_at,
  payload_hash,
  raw_created_at,
  raw_updated_at,
  {{ health_clean_text("payload_jsonb ->> 'id'") }} as payload_id,
  {{ health_clean_text("payload_jsonb ->> 'profileId'") }} as profile_id,
  {{ health_clean_text("payload_jsonb ->> 'connectionRequestId'") }} as connection_request_id,
  {{ health_clean_text("payload_jsonb ->> 'garminGUID'") }} as garmin_guid,
  {{ health_clean_text("payload_jsonb ->> 'externalId'") }} as profile_external_id,
  {{ health_clean_text("payload_jsonb ->> 'displayName'") }} as display_name,
  {{ health_clean_text("payload_jsonb ->> 'fullName'") }} as full_name,
  {{ health_clean_text("payload_jsonb ->> 'userName'") }} as user_name,
  {{ health_clean_text("payload_jsonb ->> 'userProfileFullName'") }} as user_profile_full_name,
  {{ health_clean_text("payload_jsonb ->> 'profileImageType'") }} as profile_image_type,
  {{ health_clean_text("payload_jsonb ->> 'profileImageUuid'") }} as profile_image_uuid,
  {{ health_clean_text("payload_jsonb ->> 'profileImageUrlLarge'") }} as profile_image_url_large,
  {{ health_clean_text("payload_jsonb ->> 'profileImageUrlMedium'") }} as profile_image_url_medium,
  {{ health_clean_text("payload_jsonb ->> 'profileImageUrlSmall'") }} as profile_image_url_small,
  {{ health_clean_text("payload_jsonb ->> 'location'") }} as location,
  {{ health_clean_text("payload_jsonb ->> 'facebookUrl'") }} as facebook_url,
  {{ health_clean_text("payload_jsonb ->> 'twitterUrl'") }} as twitter_url,
  {{ health_clean_text("payload_jsonb ->> 'personalWebsite'") }} as personal_website,
  {{ health_clean_text("payload_jsonb ->> 'motivation'") }} as motivation,
  {{ health_clean_text("payload_jsonb ->> 'bio'") }} as bio,
  {{ health_clean_text("payload_jsonb ->> 'primaryActivity'") }} as primary_activity,
  {{ health_clean_text("payload_jsonb ->> 'otherPrimaryActivity'") }} as other_primary_activity,
  {{ health_json_try_numeric("payload_jsonb -> 'runningTrainingSpeed'") }} as running_training_speed,
  {{ health_json_try_numeric("payload_jsonb -> 'cyclingTrainingSpeed'") }} as cycling_training_speed,
  {{ health_json_try_numeric("payload_jsonb -> 'swimmingTrainingSpeed'") }} as swimming_training_speed,
  {{ health_clean_text("payload_jsonb ->> 'cyclingClassification'") }} as cycling_classification,
  {{ health_json_try_numeric("payload_jsonb -> 'cyclingMaxAvgPower'") }} as cycling_max_avg_power,
  {{ health_clean_text("payload_jsonb ->> 'otherActivity'") }} as other_activity,
  {{ health_clean_text("payload_jsonb ->> 'otherMotivation'") }} as other_motivation,
  {{ health_clean_text("payload_jsonb ->> 'profileVisibility'") }} as profile_visibility,
  {{ health_clean_text("payload_jsonb ->> 'activityStartVisibility'") }} as activity_start_visibility,
  {{ health_clean_text("payload_jsonb ->> 'activityMapVisibility'") }} as activity_map_visibility,
  {{ health_clean_text("payload_jsonb ->> 'courseVisibility'") }} as course_visibility,
  {{ health_clean_text("payload_jsonb ->> 'activityHeartRateVisibility'") }} as activity_heart_rate_visibility,
  {{ health_clean_text("payload_jsonb ->> 'activityPowerVisibility'") }} as activity_power_visibility,
  {{ health_clean_text("payload_jsonb ->> 'badgeVisibility'") }} as badge_visibility,
  {{ health_json_try_boolean("payload_jsonb -> 'showAge'") }} as show_age,
  {{ health_json_try_boolean("payload_jsonb -> 'showWeight'") }} as show_weight,
  {{ health_json_try_boolean("payload_jsonb -> 'showHeight'") }} as show_height,
  {{ health_json_try_numeric("payload_jsonb -> 'heightCm'") }} as height_cm,
  {{ health_json_try_boolean("payload_jsonb -> 'showWeightClass'") }} as show_weight_class,
  {{ health_json_try_boolean("payload_jsonb -> 'showAgeRange'") }} as show_age_range,
  {{ health_json_try_boolean("payload_jsonb -> 'showGender'") }} as show_gender,
  {{ health_json_try_boolean("payload_jsonb -> 'showActivityClass'") }} as show_activity_class,
  {{ health_json_try_boolean("payload_jsonb -> 'showVO2Max'") }} as show_vo2_max,
  {{ health_json_try_boolean("payload_jsonb -> 'showPersonalRecords'") }} as show_personal_records,
  {{ health_json_try_boolean("payload_jsonb -> 'showLast12Months'") }} as show_last_12_months,
  {{ health_json_try_boolean("payload_jsonb -> 'showLifetimeTotals'") }} as show_lifetime_totals,
  {{ health_json_try_boolean("payload_jsonb -> 'showUpcomingEvents'") }} as show_upcoming_events,
  {{ health_json_try_boolean("payload_jsonb -> 'showRecentFavorites'") }} as show_recent_favorites,
  {{ health_json_try_boolean("payload_jsonb -> 'showRecentDevice'") }} as show_recent_device,
  {{ health_json_try_boolean("payload_jsonb -> 'showRecentGear'") }} as show_recent_gear,
  {{ health_json_try_boolean("payload_jsonb -> 'showBadges'") }} as show_badges,
  {{ health_json_try_boolean("payload_jsonb -> 'nameApproved'") }} as name_approved,
  {{ health_json_try_boolean("payload_jsonb -> 'makeGolfScorecardsPrivate'") }} as make_golf_scorecards_private,
  {{ health_json_try_boolean("payload_jsonb -> 'allowGolfLiveScoring'") }} as allow_golf_live_scoring,
  {{ health_json_try_boolean("payload_jsonb -> 'allowGolfScoringByConnections'") }} as allow_golf_scoring_by_connections,
  {{ health_json_try_integer("payload_jsonb -> 'userLevel'") }} as user_level,
  {{ health_json_try_integer("payload_jsonb -> 'userPoint'") }} as user_point,
  {{ health_clean_text("payload_jsonb ->> 'levelUpdateDate'") }} as level_update_at,
  {{ health_json_try_boolean("payload_jsonb -> 'levelIsViewed'") }} as level_is_viewed,
  {{ health_json_try_integer("payload_jsonb -> 'levelPointThreshold'") }} as level_point_threshold,
  {{ health_json_try_integer("payload_jsonb -> 'userPointOffset'") }} as user_point_offset,
  {{ health_json_try_boolean("payload_jsonb -> 'userPro'") }} as user_pro

from source_records
