{{ config(tags=['garmin', 'health', 'staging']) }}

with source_records as (
    select
      id as raw_record_id,
      account_id,
      connector_config_id,
      sync_task_id,
      connector_id,
      source_stream,
      external_id as source_external_id,
      source_record_date,
      source_record_at,
      source_updated_at,
      collected_at,
      payload_hash,
      created_at as raw_created_at,
      updated_at as raw_updated_at,
      payload_jsonb
    from {{ source('raw_health', 'health_snapshot_record') }}
    where connector_id = 'garmin-connect'
      and source_stream = 'sleep'
),
normalized as (
    select
      *,
      {{ health_json_object_or_empty("payload_jsonb -> 'dailySleepDTO'") }} as daily_sleep_dto,
      {{ health_json_object_or_empty("payload_jsonb #> '{dailySleepDTO,sleepScores}'") }} as sleep_scores
    from source_records
)
select
  raw_record_id,
  account_id,
  connector_config_id,
  sync_task_id,
  connector_id,
  source_stream,
  source_external_id,
  source_record_date,
  source_record_at,
  source_updated_at,
  collected_at,
  payload_hash,
  raw_created_at,
  raw_updated_at,
  {{ health_clean_text("daily_sleep_dto ->> 'id'") }} as sleep_id,
  {{ health_clean_text("daily_sleep_dto ->> 'userProfilePK'") }} as user_profile_pk,
  {{ health_clean_text("daily_sleep_dto ->> 'calendarDate'") }} as calendar_date,
  {{ health_json_try_bigint("daily_sleep_dto -> 'sleepTimeSeconds'") }} as sleep_time_seconds,
  {{ health_json_try_bigint("daily_sleep_dto -> 'napTimeSeconds'") }} as nap_time_seconds,
  {{ health_json_try_boolean("daily_sleep_dto -> 'sleepWindowConfirmed'") }} as sleep_window_confirmed,
  {{ health_clean_text("daily_sleep_dto ->> 'sleepWindowConfirmationType'") }} as sleep_window_confirmation_type,
  {{ health_clean_text("daily_sleep_dto ->> 'sleepStartTimestampGMT'") }} as sleep_start_timestamp_gmt,
  {{ health_clean_text("daily_sleep_dto ->> 'sleepEndTimestampGMT'") }} as sleep_end_timestamp_gmt,
  {{ health_clean_text("daily_sleep_dto ->> 'sleepStartTimestampLocal'") }} as sleep_start_timestamp_local,
  {{ health_clean_text("daily_sleep_dto ->> 'sleepEndTimestampLocal'") }} as sleep_end_timestamp_local,
  {{ health_clean_text("daily_sleep_dto ->> 'autoSleepStartTimestampGMT'") }} as auto_sleep_start_timestamp_gmt,
  {{ health_clean_text("daily_sleep_dto ->> 'autoSleepEndTimestampGMT'") }} as auto_sleep_end_timestamp_gmt,
  {{ health_clean_text("daily_sleep_dto ->> 'sleepQualityTypePK'") }} as sleep_quality_type_pk,
  {{ health_clean_text("daily_sleep_dto ->> 'sleepResultTypePK'") }} as sleep_result_type_pk,
  {{ health_json_try_bigint("daily_sleep_dto -> 'unmeasurableSleepSeconds'") }} as unmeasurable_sleep_seconds,
  {{ health_json_try_bigint("daily_sleep_dto -> 'deepSleepSeconds'") }} as deep_sleep_seconds,
  {{ health_json_try_bigint("daily_sleep_dto -> 'lightSleepSeconds'") }} as light_sleep_seconds,
  {{ health_json_try_bigint("daily_sleep_dto -> 'remSleepSeconds'") }} as rem_sleep_seconds,
  {{ health_json_try_bigint("daily_sleep_dto -> 'awakeSleepSeconds'") }} as awake_sleep_seconds,
  {{ health_json_try_boolean("daily_sleep_dto -> 'deviceRemCapable'") }} as device_rem_capable,
  {{ health_json_try_boolean("daily_sleep_dto -> 'retro'") }} as retro,
  {{ health_json_try_boolean("daily_sleep_dto -> 'sleepFromDevice'") }} as sleep_from_device,
  {{ health_json_try_numeric("daily_sleep_dto -> 'averageRespirationValue'") }} as average_respiration_value,
  {{ health_json_try_numeric("daily_sleep_dto -> 'lowestRespirationValue'") }} as lowest_respiration_value,
  {{ health_json_try_numeric("daily_sleep_dto -> 'highestRespirationValue'") }} as highest_respiration_value,
  {{ health_json_try_integer("daily_sleep_dto -> 'awakeCount'") }} as awake_count,
  {{ health_json_try_numeric("daily_sleep_dto -> 'avgSleepStress'") }} as avg_sleep_stress,
  {{ health_clean_text("daily_sleep_dto ->> 'ageGroup'") }} as age_group,
  {{ health_clean_text("daily_sleep_dto ->> 'sleepScoreFeedback'") }} as sleep_score_feedback,
  {{ health_clean_text("daily_sleep_dto ->> 'sleepScoreInsight'") }} as sleep_score_insight,
  {{ health_clean_text("daily_sleep_dto ->> 'sleepScorePersonalizedInsight'") }} as sleep_score_personalized_insight,
  {{ health_clean_text("daily_sleep_dto ->> 'sleepVersion'") }} as sleep_version,
  {{ health_clean_text("sleep_scores #>> '{totalDuration,qualifierKey}'") }} as total_duration_score_qualifier_key,
  {{ health_json_try_numeric("sleep_scores #> '{totalDuration,optimalStart}'") }} as total_duration_score_optimal_start,
  {{ health_json_try_numeric("sleep_scores #> '{totalDuration,optimalEnd}'") }} as total_duration_score_optimal_end,
  {{ health_clean_text("sleep_scores #>> '{stress,qualifierKey}'") }} as stress_score_qualifier_key,
  {{ health_json_try_numeric("sleep_scores #> '{stress,optimalStart}'") }} as stress_score_optimal_start,
  {{ health_json_try_numeric("sleep_scores #> '{stress,optimalEnd}'") }} as stress_score_optimal_end,
  {{ health_clean_text("sleep_scores #>> '{awakeCount,qualifierKey}'") }} as awake_count_score_qualifier_key,
  {{ health_json_try_numeric("sleep_scores #> '{awakeCount,optimalStart}'") }} as awake_count_score_optimal_start,
  {{ health_json_try_numeric("sleep_scores #> '{awakeCount,optimalEnd}'") }} as awake_count_score_optimal_end,
  {{ health_json_try_numeric("sleep_scores #> '{overall,value}'") }} as overall_score_value,
  {{ health_clean_text("sleep_scores #>> '{overall,qualifierKey}'") }} as overall_score_qualifier_key,
  {{ health_json_try_numeric("sleep_scores #> '{remPercentage,value}'") }} as rem_percentage_score_value,
  {{ health_clean_text("sleep_scores #>> '{remPercentage,qualifierKey}'") }} as rem_percentage_score_qualifier_key,
  {{ health_json_try_numeric("sleep_scores #> '{remPercentage,idealStartInSeconds}'") }} as rem_percentage_score_ideal_start_in_seconds,
  {{ health_json_try_numeric("sleep_scores #> '{remPercentage,idealEndInSeconds}'") }} as rem_percentage_score_ideal_end_in_seconds,
  {{ health_json_try_numeric("sleep_scores #> '{remPercentage,optimalStart}'") }} as rem_percentage_score_optimal_start,
  {{ health_json_try_numeric("sleep_scores #> '{remPercentage,optimalEnd}'") }} as rem_percentage_score_optimal_end,
  {{ health_json_try_numeric("sleep_scores #> '{lightPercentage,value}'") }} as light_percentage_score_value,
  {{ health_clean_text("sleep_scores #>> '{lightPercentage,qualifierKey}'") }} as light_percentage_score_qualifier_key,
  {{ health_json_try_numeric("sleep_scores #> '{lightPercentage,idealStartInSeconds}'") }} as light_percentage_score_ideal_start_in_seconds,
  {{ health_json_try_numeric("sleep_scores #> '{lightPercentage,idealEndInSeconds}'") }} as light_percentage_score_ideal_end_in_seconds,
  {{ health_json_try_numeric("sleep_scores #> '{lightPercentage,optimalStart}'") }} as light_percentage_score_optimal_start,
  {{ health_json_try_numeric("sleep_scores #> '{lightPercentage,optimalEnd}'") }} as light_percentage_score_optimal_end,
  {{ health_json_try_numeric("sleep_scores #> '{deepPercentage,value}'") }} as deep_percentage_score_value,
  {{ health_clean_text("sleep_scores #>> '{deepPercentage,qualifierKey}'") }} as deep_percentage_score_qualifier_key,
  {{ health_json_try_numeric("sleep_scores #> '{deepPercentage,idealStartInSeconds}'") }} as deep_percentage_score_ideal_start_in_seconds,
  {{ health_json_try_numeric("sleep_scores #> '{deepPercentage,idealEndInSeconds}'") }} as deep_percentage_score_ideal_end_in_seconds,
  {{ health_json_try_numeric("sleep_scores #> '{deepPercentage,optimalStart}'") }} as deep_percentage_score_optimal_start,
  {{ health_json_try_numeric("sleep_scores #> '{deepPercentage,optimalEnd}'") }} as deep_percentage_score_optimal_end,
  {{ health_clean_text("sleep_scores #>> '{restlessness,qualifierKey}'") }} as restlessness_score_qualifier_key,
  {{ health_json_try_numeric("sleep_scores #> '{restlessness,optimalStart}'") }} as restlessness_score_optimal_start,
  {{ health_json_try_numeric("sleep_scores #> '{restlessness,optimalEnd}'") }} as restlessness_score_optimal_end,
  {{ health_json_try_boolean("payload_jsonb -> 'remSleepData'") }} as rem_sleep_data,
  {{ health_json_try_integer("payload_jsonb -> 'restlessMomentsCount'") }} as restless_moments_count,
  {{ health_json_try_boolean("payload_jsonb -> 'skinTempDataExists'") }} as skin_temp_data_exists,
  {{ health_json_try_numeric("payload_jsonb -> 'avgOvernightHrv'") }} as avg_overnight_hrv,
  {{ health_clean_text("payload_jsonb ->> 'hrvStatus'") }} as hrv_status,
  {{ health_json_try_numeric("payload_jsonb -> 'bodyBatteryChange'") }} as body_battery_change,
  {{ health_json_try_integer("payload_jsonb -> 'restingHeartRate'") }} as resting_heart_rate,
  {{ health_json_try_integer("payload_jsonb -> 'respirationVersion'") }} as respiration_version

from normalized
