{{ config(tags=['garmin', 'health', 'staging']) }}

with source_records as (
    select
      id as raw_record_id,
      account_id,
      connector_config_id,
      sync_task_id,
      connector_id,
      source_stream,
      external_id as source_external_id,
      source_record_date,
      source_record_at,
      source_updated_at,
      collected_at,
      payload_hash,
      created_at as raw_created_at,
      updated_at as raw_updated_at,
      payload_jsonb
    from {{ source('raw_health', 'health_event_record') }}
    where connector_id = 'garmin-connect'
      and source_stream = 'activity'
)
select
  raw_record_id,
  account_id,
  connector_config_id,
  sync_task_id,
  connector_id,
  source_stream,
  source_external_id,
  source_record_date,
  source_record_at,
  source_updated_at,
  collected_at,
  payload_hash,
  raw_created_at,
  raw_updated_at,
  {{ health_clean_text("payload_jsonb ->> 'activityId'") }} as activity_id,
  {{ health_clean_text("payload_jsonb ->> 'activityUUID'") }} as activity_uuid,
  {{ health_clean_text("payload_jsonb ->> 'deviceId'") }} as device_id,
  {{ health_clean_text("payload_jsonb ->> 'activityName'") }} as activity_name,
  {{ health_json_try_boolean("payload_jsonb -> 'favorite'") }} as favorite,
  {{ health_json_try_boolean("payload_jsonb -> 'manualActivity'") }} as manual_activity,
  {{ health_json_try_boolean("payload_jsonb -> 'purposeful'") }} as purposeful,
  {{ health_json_try_boolean("payload_jsonb -> 'pr'") }} as pr,
  {{ health_json_try_boolean("payload_jsonb -> 'parent'") }} as parent,
  {{ health_json_try_boolean("payload_jsonb -> 'userPro'") }} as user_pro,
  {{ health_json_try_boolean("payload_jsonb -> 'decoDive'") }} as deco_dive,
  {{ health_json_try_boolean("payload_jsonb -> 'qualifyingDive'") }} as qualifying_dive,
  {{ health_json_try_boolean("payload_jsonb -> 'atpActivity'") }} as atp_activity,
  {{ health_json_try_boolean("payload_jsonb -> 'autoCalcCalories'") }} as auto_calc_calories,
  {{ health_json_try_boolean("payload_jsonb -> 'elevationCorrected'") }} as elevation_corrected,
  {{ health_json_try_boolean("payload_jsonb -> 'hasPolyline'") }} as has_polyline,
  {{ health_json_try_boolean("payload_jsonb -> 'hasImages'") }} as has_images,
  {{ health_json_try_boolean("payload_jsonb -> 'hasHeatMap'") }} as has_heat_map,
  {{ health_json_try_boolean("payload_jsonb -> 'hasSplits'") }} as has_splits,
  {{ health_json_try_boolean("payload_jsonb -> 'hasVideo'") }} as has_video,
  {{ health_clean_text("payload_jsonb #>> '{eventType,typeKey}'") }} as event_type_type_key,
  {{ health_json_try_integer("payload_jsonb #> '{eventType,typeId}'") }} as event_type_type_id,
  {{ health_json_try_integer("payload_jsonb #> '{eventType,sortOrder}'") }} as event_type_sort_order,
  {{ health_json_try_integer("payload_jsonb #> '{activityType,typeId}'") }} as activity_type_type_id,
  {{ health_clean_text("payload_jsonb #>> '{activityType,typeKey}'") }} as activity_type_type_key,
  {{ health_json_try_integer("payload_jsonb #> '{activityType,parentTypeId}'") }} as activity_type_parent_type_id,
  {{ health_json_try_boolean("payload_jsonb #> '{activityType,isHidden}'") }} as activity_type_is_hidden,
  {{ health_json_try_boolean("payload_jsonb #> '{activityType,restricted}'") }} as activity_type_restricted,
  {{ health_json_try_boolean("payload_jsonb #> '{activityType,trimmable}'") }} as activity_type_trimmable,
  {{ health_clean_text("payload_jsonb ->> 'startTimeLocal'") }} as start_time_local,
  {{ health_clean_text("payload_jsonb ->> 'startTimeGMT'") }} as start_time_gmt,
  {{ health_clean_text("payload_jsonb ->> 'endTimeGMT'") }} as end_time_gmt,
  {{ health_clean_text("payload_jsonb ->> 'beginTimestamp'") }} as begin_timestamp,
  {{ health_clean_text("payload_jsonb ->> 'timeZoneId'") }} as time_zone_id,
  {{ health_json_try_numeric("payload_jsonb -> 'startLatitude'") }} as start_latitude,
  {{ health_json_try_numeric("payload_jsonb -> 'startLongitude'") }} as start_longitude,
  {{ health_json_try_numeric("payload_jsonb -> 'endLatitude'") }} as end_latitude,
  {{ health_json_try_numeric("payload_jsonb -> 'endLongitude'") }} as end_longitude,
  {{ health_json_try_numeric("payload_jsonb -> 'distance'") }} as distance,
  {{ health_json_try_numeric("payload_jsonb -> 'duration'") }} as duration,
  {{ health_json_try_numeric("payload_jsonb -> 'movingDuration'") }} as moving_duration,
  {{ health_json_try_numeric("payload_jsonb -> 'elapsedDuration'") }} as elapsed_duration,
  {{ health_json_try_numeric("payload_jsonb -> 'elevationGain'") }} as elevation_gain,
  {{ health_json_try_numeric("payload_jsonb -> 'elevationLoss'") }} as elevation_loss,
  {{ health_json_try_numeric("payload_jsonb -> 'maxElevation'") }} as max_elevation,
  {{ health_json_try_numeric("payload_jsonb -> 'minElevation'") }} as min_elevation,
  {{ health_json_try_numeric("payload_jsonb -> 'averageSpeed'") }} as average_speed,
  {{ health_json_try_numeric("payload_jsonb -> 'maxSpeed'") }} as max_speed,
  {{ health_json_try_numeric("payload_jsonb -> 'calories'") }} as calories,
  {{ health_json_try_numeric("payload_jsonb -> 'bmrCalories'") }} as bmr_calories,
  {{ health_json_try_integer("payload_jsonb -> 'averageHR'") }} as average_hr,
  {{ health_json_try_integer("payload_jsonb -> 'maxHR'") }} as max_hr,
  {{ health_json_try_numeric("payload_jsonb -> 'aerobicTrainingEffect'") }} as aerobic_training_effect,
  {{ health_json_try_numeric("payload_jsonb -> 'anaerobicTrainingEffect'") }} as anaerobic_training_effect,
  {{ health_clean_text("payload_jsonb ->> 'aerobicTrainingEffectMessage'") }} as aerobic_training_effect_message,
  {{ health_clean_text("payload_jsonb ->> 'anaerobicTrainingEffectMessage'") }} as anaerobic_training_effect_message,
  {{ health_clean_text("payload_jsonb ->> 'trainingEffectLabel'") }} as training_effect_label,
  {{ health_json_try_numeric("payload_jsonb -> 'activityTrainingLoad'") }} as activity_training_load,
  {{ health_json_try_numeric("payload_jsonb -> 'minActivityLapDuration'") }} as min_activity_lap_duration,
  {{ health_json_try_numeric("payload_jsonb -> 'moderateIntensityMinutes'") }} as moderate_intensity_minutes,
  {{ health_json_try_numeric("payload_jsonb -> 'vigorousIntensityMinutes'") }} as vigorous_intensity_minutes,
  {{ health_json_try_numeric("payload_jsonb -> 'differenceBodyBattery'") }} as difference_body_battery,
  {{ health_json_try_numeric("payload_jsonb -> 'maxVerticalSpeed'") }} as max_vertical_speed,
  {{ health_json_try_numeric("payload_jsonb -> 'fastestSplit_40000'") }} as fastest_split_40000,
  {{ health_json_try_integer("payload_jsonb -> 'lapCount'") }} as lap_count,
  {{ health_json_try_numeric("payload_jsonb -> 'maxFtp'") }} as max_ftp,
  {{ health_json_try_integer("payload_jsonb -> 'sportTypeId'") }} as sport_type_id,
  {{ health_json_try_bigint("payload_jsonb -> 'hrTimeInZone_1'") }} as hr_time_in_zone_1,
  {{ health_json_try_bigint("payload_jsonb -> 'hrTimeInZone_2'") }} as hr_time_in_zone_2,
  {{ health_json_try_bigint("payload_jsonb -> 'hrTimeInZone_3'") }} as hr_time_in_zone_3,
  {{ health_json_try_bigint("payload_jsonb -> 'hrTimeInZone_4'") }} as hr_time_in_zone_4,
  {{ health_json_try_bigint("payload_jsonb -> 'hrTimeInZone_5'") }} as hr_time_in_zone_5,
  {{ health_clean_text("payload_jsonb ->> 'manufacturer'") }} as manufacturer,
  {{ health_clean_text("payload_jsonb ->> 'locationName'") }} as location_name,
  {{ health_clean_text("payload_jsonb ->> 'ownerId'") }} as owner_id,
  {{ health_clean_text("payload_jsonb ->> 'ownerDisplayName'") }} as owner_display_name,
  {{ health_clean_text("payload_jsonb ->> 'ownerFullName'") }} as owner_full_name,
  {{ health_clean_text("payload_jsonb ->> 'ownerProfileImageUrlLarge'") }} as owner_profile_image_url_large,
  {{ health_clean_text("payload_jsonb ->> 'ownerProfileImageUrlMedium'") }} as owner_profile_image_url_medium,
  {{ health_clean_text("payload_jsonb ->> 'ownerProfileImageUrlSmall'") }} as owner_profile_image_url_small,
  {{ health_json_try_integer("payload_jsonb #> '{privacy,typeId}'") }} as privacy_type_id,
  {{ health_clean_text("payload_jsonb #>> '{privacy,typeKey}'") }} as privacy_type_key,
  {{ health_clean_text("payload_jsonb ->> 'waterEstimated'") }} as water_estimated

from source_records
